server:
  port: 8082

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey=: ${JWT_PUBLIC_KEY}

spring:
  application:
    name: indentity
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect